version: "3.7"

services:
  ros2-dev:
    image: ghcr.io/kerrys-learning-lab/devcontainer-ros2:latest
    entrypoint: bash -c "while true; do sleep 1000; done"
    user: vscode
    volumes:
      - source: ..
        target: /workspace
        type: bind
      - source: /var/run/docker.sock
        target: /var/run/docker.sock
        type: bind
      - source: ${HOME}/.ssh
        target: /home/vscode/.ssh
        type: bind
