name: Docker image workflow

on:
  push:
  create:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern=v{{version}}
            type=sha,prefix=${{ github.ref_name }}--{{ date 'YYYY-MM-DD' }}--
            type=raw,value=latest,enable=${{ startsWith( github.ref, 'refs/tags/v') }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ startsWith( github.ref, 'refs/tags/v') || contains(github.event.head_commit.message, '[test ci]') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  bump-version:
    needs: build-and-push-image
    if: (github.ref_protected && !startsWith(github.event.head_commit.message, 'bump:') )
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: "${{ secrets.GITHUB_TOKEN }}"
      - id: cz
        name: Update version and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.ACTIONS_REPO_TOKEN }}
          git_name: ${{ github.repository_owner }}-actions
          git_email: ${{ github.repository_owner }}-actions[bot]@users.noreply.github.com
      - name: Print Version
        run: echo "${{ steps.cz.outputs.version }}"
